const DEBUG = true;

const IMPACT_DISTANCE = 30;

const PLAYER_WIDTH = 20;
const PLAYER_HEIGHT = 46;

const TILESIZE = 64;

const DEFAULTSPAWNX = 30 * TILESIZE;
const DEFAULTSPAWNY = 27 * TILESIZE;

const WIDTH = 1280;
const HEIGHT = 720;

const MINHEIGHT = 0;
const MINWIDTH = 0;

const MAXHEIGHT = 100*TILESIZE;
const MAXWIDTH = 100*TILESIZE;

module.exports = {
  DEBUG,
  IMPACT_DISTANCE,
  PLAYER_WIDTH,
  PLAYER_HEIGHT,
  TILESIZE,
  DEFAULTSPAWNX,
  DEFAULTSPAWNY,
  WIDTH,
  HEIGHT,
  MINHEIGHT,
  MINWIDTH,
  MAXHEIGHT,
  MAXWIDTH
}
